"""add paused at to sessions

Revision ID: 182ed49bbc5a
Revises: 67d40102b40b
Create Date: 2026-10-01 23:27:53.126677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '182ed49bbc5a'
down_revision: Union[str, Sequence[str], None] = '67d40102b40b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'paused_at')
    # ### end Alembic commands ###
