"""add postguard monitoring tables

Revision ID: 438259405319
Revises: 960c9656de8b
Create Date: 2026-09-30 19:33:57.500917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '438259405319'
down_revision: Union[str, Sequence[str], None] = '960c9656de8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('camera_name', sa.String(length=255), nullable=False),
    sa.Column('resolution_width', sa.Integer(), nullable=False),
    sa.Column('resolution_height', sa.Integer(), nullable=False),
    sa.Column('reprojection_error', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('camera_id')
    )
    op.create_index(op.f('ix_cameras_camera_id'), 'cameras', ['camera_id'], unique=False)
    op.create_index(op.f('ix_cameras_user_id'), 'cameras', ['user_id'], unique=False)
    op.create_table('personal_baselines',
    sa.Column('baseline_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('neck_flexion_baseline', sa.Float(), nullable=True),
    sa.Column('shoulder_angle', sa.Float(), nullable=True),
    sa.Column('lateral_tilt_baseline', sa.Float(), nullable=True),
    sa.Column('shoulder_tilt_status', sa.String(length=20), nullable=True),
    sa.Column('forward_head_baseline', sa.Float(), nullable=True),
    sa.Column('neck_rotation_baseline', sa.Float(), nullable=True),
    sa.Column('shoulder_level_difference_baseline', sa.Float(), nullable=True),
    sa.Column('ipd_baseline', sa.Float(), nullable=True),
    sa.Column('screen_distance_baseline', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('baseline_id')
    )
    op.create_index(op.f('ix_personal_baselines_baseline_id'), 'personal_baselines', ['baseline_id'], unique=False)
    op.create_index(op.f('ix_personal_baselines_camera_id'), 'personal_baselines', ['camera_id'], unique=False)
    op.create_index(op.f('ix_personal_baselines_user_id'), 'personal_baselines', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('baseline_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_duration', sa.Integer(), nullable=False),
    sa.Column('paused_duration', sa.Integer(), nullable=False),
    sa.Column('pause_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['baseline_id'], ['personal_baselines.baseline_id'], ),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_baseline_id'), 'sessions', ['baseline_id'], unique=False)
    op.create_index(op.f('ix_sessions_camera_id'), 'sessions', ['camera_id'], unique=False)
    op.create_index(op.f('ix_sessions_session_id'), 'sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('alert_events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_alert_events_event_id'), 'alert_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_alert_events_session_id'), 'alert_events', ['session_id'], unique=False)
    op.create_table('session_summaries',
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('average_risk_score', sa.Float(), nullable=False),
    sa.Column('maximum_risk_score', sa.Float(), nullable=False),
    sa.Column('low_risk_duration', sa.Integer(), nullable=False),
    sa.Column('medium_risk_duration', sa.Integer(), nullable=False),
    sa.Column('high_risk_duration', sa.Integer(), nullable=False),
    sa.Column('low_risk_alert_count', sa.Integer(), nullable=False),
    sa.Column('medium_risk_alert_count', sa.Integer(), nullable=False),
    sa.Column('high_risk_alert_count', sa.Integer(), nullable=False),
    sa.Column('total_alert_count', sa.Integer(), nullable=False),
    sa.Column('most_frequent_alert_event', sa.String(length=100), nullable=True),
    sa.Column('blink_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('summary_id')
    )
    op.create_index(op.f('ix_session_summaries_session_id'), 'session_summaries', ['session_id'], unique=True)
    op.create_index(op.f('ix_session_summaries_summary_id'), 'session_summaries', ['summary_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_summaries_summary_id'), table_name='session_summaries')
    op.drop_index(op.f('ix_session_summaries_session_id'), table_name='session_summaries')
    op.drop_table('session_summaries')
    op.drop_index(op.f('ix_alert_events_session_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_event_id'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_camera_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_baseline_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_personal_baselines_user_id'), table_name='personal_baselines')
    op.drop_index(op.f('ix_personal_baselines_camera_id'), table_name='personal_baselines')
    op.drop_index(op.f('ix_personal_baselines_baseline_id'), table_name='personal_baselines')
    op.drop_table('personal_baselines')
    op.drop_index(op.f('ix_cameras_user_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_camera_id'), table_name='cameras')
    op.drop_table('cameras')
    # ### end Alembic commands ###
