"""add reset token tracking

Revision ID: 960c9656de8b
Revises: a7e401af1230
Create Date: 2026-09-24 01:17:15.380948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '960c9656de8b'
down_revision: Union[str, Sequence[str], None] = 'a7e401af1230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset', sa.Column('reset_token_jti', sa.String(length=50), nullable=True))
    op.add_column('password_reset', sa.Column('reset_token_used_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'password_reset', ['reset_token_jti'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'password_reset', type_='unique')
    op.drop_column('password_reset', 'reset_token_used_at')
    op.drop_column('password_reset', 'reset_token_jti')
    # ### end Alembic commands ###
